# Generated by Django 4.0.4 on 2022-08-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('nid', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_owner', models.CharField(choices=[('R', 'Rentee'), ('S', 'Spot Owner')], default='user', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
