# Generated by Django 4.0.4 on 2022-08-26 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('nid', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='nid')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('contact', models.CharField(max_length=15, null=True, verbose_name='contact')),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True, verbose_name='last_login')),
                ('is_owner', models.CharField(choices=[('R', 'Rentee'), ('S', 'Spot Owner'), ('D', 'Driver')], default='user', max_length=10, verbose_name='is_owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='spot_id')),
                ('spot_road', models.CharField(max_length=200, verbose_name='spot_road')),
                ('spot_area', models.CharField(max_length=200, verbose_name='spot_area')),
                ('spot_house', models.CharField(max_length=200, verbose_name='spot_house')),
                ('spot_maps_url', models.CharField(max_length=200, null=True, verbose_name='spot_maps_url')),
                ('spot_desc', models.CharField(max_length=200, null=True, verbose_name='spot_desc')),
                ('spot_number', models.CharField(max_length=200, null=True, verbose_name='spot_number')),
                ('spot_owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_1', models.CharField(default='9:00AM-11:00AM', max_length=200, verbose_name='slot_1')),
                ('slot_2', models.CharField(default='11:00AM-1:00PM', max_length=200, verbose_name='slot_2')),
                ('slot_3', models.CharField(default='1:00PM-3:00PM', max_length=200, verbose_name='slot_3')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.spot')),
            ],
        ),
        migrations.CreateModel(
            name='SpotOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentee_balance', models.CharField(default=0, max_length=10, verbose_name='rentee_balance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(default=None, max_length=30, null=True, verbose_name='driver_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
