# Generated by Django 4.0.4 on 2022-08-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact',
            field=models.CharField(max_length=15, null=True, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=200, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_owner',
            field=models.CharField(choices=[('R', 'Rentee'), ('S', 'Spot Owner')], default='user', max_length=10, verbose_name='is_owner'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='last_login'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='nid'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
