# Generated by Django 4.0.4 on 2022-08-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslots',
            name='slot_4',
            field=models.CharField(default='3:00PM-5:00PM', max_length=200, verbose_name='slot_4'),
        ),
    ]
