# Generated by Django 4.0.4 on 2022-08-22 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_users_contact_alter_users_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenteeTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='transaction_id')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='transaction_date')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='review_id')),
                ('review_text', models.CharField(max_length=200, verbose_name='review_text')),
                ('review_rating', models.IntegerField(default=0, verbose_name='review_rating')),
                ('review_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='review_date')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='spot_id')),
                ('spot_name', models.CharField(max_length=200, verbose_name='spot_name')),
                ('spot_road_no', models.CharField(max_length=200, verbose_name='spot_road_no')),
                ('spot_area', models.CharField(max_length=200, verbose_name='spot_area')),
                ('spot_house_no', models.CharField(max_length=200, verbose_name='spot_house_no')),
                ('spot_city', models.CharField(max_length=200, verbose_name='spot_city')),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('timing_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='timing_id')),
                ('timing_start', models.TimeField(verbose_name='timing_start')),
                ('timing_end', models.TimeField(verbose_name='timing_end')),
                ('timing_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.spot')),
            ],
        ),
        migrations.CreateModel(
            name='SpotOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('spot_ids', models.ManyToManyField(blank=True, to='home.spot')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='spot',
            name='spot_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.spotowner'),
        ),
        migrations.AddField(
            model_name='spot',
            name='spot_reviews',
            field=models.ManyToManyField(blank=True, to='home.review'),
        ),
        migrations.AddField(
            model_name='spot',
            name='spot_timings',
            field=models.ManyToManyField(blank=True, to='home.timing'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.spot'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentee_balance', models.IntegerField(default=0)),
                ('rentee_spot_ids', models.ManyToManyField(blank=True, to='home.spot')),
                ('rentee_transactions', models.ManyToManyField(blank=True, to='home.renteetransaction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driver_phone', models.IntegerField(default=0)),
                ('driver_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='driver_id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
