# Generated by Django 4.0.4 on 2022-08-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_timeslots_slot_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='spot_times',
            field=models.CharField(default='', max_length=200, verbose_name='spot_times'),
        ),
    ]
