# Generated by Django 4.0.4 on 2022-08-23 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_renteetransaction_review_spot_timing_spotowner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='spot_contact',
            field=models.CharField(max_length=200, null=True, verbose_name='spot_contact'),
        ),
        migrations.AddField(
            model_name='spot',
            name='spot_desc',
            field=models.CharField(max_length=200, null=True, verbose_name='spot_desc'),
        ),
        migrations.AddField(
            model_name='spot',
            name='spot_maps_url',
            field=models.CharField(max_length=200, null=True, verbose_name='spot_maps_url'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='spot_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
