# Generated by Django 4.0.4 on 2022-08-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_spot_spot_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='spot_reviews',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='spot_reviews'),
        ),
    ]
