# Generated by Django 4.0.4 on 2022-08-23 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_spot_spot_contact_spot_spot_desc_spot_spot_maps_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='spot_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
