# Generated by Django 4.0.4 on 2022-08-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_spot_spot_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='driver_about_me',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='driver_about_me'),
        ),
        migrations.AddField(
            model_name='drivers',
            name='driver_area',
            field=models.CharField(default='Dhaka', max_length=30, null=True, verbose_name='driver_area'),
        ),
        migrations.AddField(
            model_name='drivers',
            name='driver_experience',
            field=models.CharField(default='2', max_length=200, null=True, verbose_name='driver_experience'),
        ),
    ]
