# Generated by Django 4.0.4 on 2022-08-24 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_spot_spot_contact_remove_spot_spot_house_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='spot_city',
        ),
        migrations.AlterField(
            model_name='spot',
            name='spot_owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
