# Generated by Django 4.0.4 on 2022-08-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_rentee_rentee_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='driver_contact',
            field=models.CharField(max_length=15, null=True, verbose_name='driver_contact'),
        ),
    ]
